In [1]:
import numpy as np
import pandas as pd

In [2]:
sales = pd.read_excel("C:\\Users\\adity\\Documents\\TableauWork\\Customer_SuperStore.xlsx")

In [3]:
sales

Customer Name  Sales  Profit
0           Aaron Bergman    886     129
1           Aaron Hawkins   1745     365
2          Aaron Smayling   3051    -254
3         Adam Bellavance   7756    2055
4               Adam Hart   3250     281
5      Adam Shillingsburg   3255      65
6           Adrian Barton  14474    5445
7             Adrian Hane   1736      -2
8            Adrian Shami     59      22
9             Aimee Bixby    967     314
10            Alan Barnes   1114     221
11         Alan Dominguez   6107    1870
12            Alan Haines   1587    -379
13             Alan Hwang   4805    1309
14      Alan Schoenberger   4261     720
15           Alan Shonely    585      34
16   Alejandro Ballentine    915     265
17        Alejandro Grove   2583     733
18       Alejandro Savely   3214     355
19    Aleksandra Gannaway    368      59
20             Alex Avila   5564    -363
21           Alex Grayson    661      -5
22           Alex Russell   1056    -221
23         Alice McCarthy    814     195
24           Allen Armold   1056     277
25         Allen Goldenen    201      69
26       Allen Rosenblatt   2236     -99
27          Alyssa Crouse    926     -62
28            Alyssa Tate   1172     101
29                Amy Cox   5528    1366
..                    ...    ...     ...
763         Tony Molinari   1095     293
764            Tony Sayre   2243      11
765       Tracy Blumstein   4737   -1603
766         Tracy Collins    743     218
767         Tracy Hopkins   4234    -572
768          Tracy Poddar   1937     139
769             Tracy Zic   1707     225
770        Troy Blackwell   1388    -136
771          Troy Staebel   2820    -295
772           Trudy Brown   2798     380
773          Trudy Glocke   2075     366
774         Trudy Schmidt   3368     221
775     Valerie Dominguez   6442    1618
776       Valerie Mitchum   2455     514
777      Valerie Takahito   1737    -224
778        Vicky Freymann    848     -96
779          Victor Preis    994     205
780      Victoria Brennan   2006     371
781      Victoria Pisteka   3361   -1019
782       Victoria Wilson   6134    -875
783        Vivek Gonzalez    846     144
784           Vivek Grady    427     -52
785      Vivek Sundaresam   1056    -263
786         Vivian Mathis    381     117
787         William Brown   6160     714
788          Xylona Preis   2375     621
789         Yana Sorensen   6720    1778
790        Yoseph Carroll   5454    1306
791      Zuschuss Carroll   8026   -1032
792    Zuschuss Donatelli   1494     249

[793 rows x 3 columns]

In [4]:
## Build a model using Linear Regression
from sklearn.linear_model import LinearRegression
model = LinearRegression()
df_X = pd.DataFrame(sales['Sales'].values)
df_Y = pd.DataFrame(sales['Profit'].values)
model.fit(df_X, df_Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
## See the LR Coefficient generated by the model
model.coef_

array([[0.17225455]])

In [6]:
## See the LR Intercept generated by the model
model.intercept_

array([-137.82807613])

In [7]:
## Predict profit using the sales values in the data source
sales_predict = model.predict(df_X)
sales_predict

array([[ 1.47894534e+01],
       [ 1.62756110e+02],
       [ 3.87720550e+02],
       [ 1.19817820e+03],
       [ 4.21999205e+02],
       [ 4.22860478e+02],
       [ 2.35538425e+03],
       [ 1.61205819e+02],
       [-1.27665058e+02],
       [ 2.87420718e+01],
       [ 5.40634903e+01],
       [ 9.14130448e+02],
       [ 1.35539892e+02],
       [ 6.89855027e+02],
       [ 5.96148553e+02],
       [-3.70591656e+01],
       [ 1.97848353e+01],
       [ 3.07105421e+02],
       [ 4.15798041e+02],
       [-7.44384025e+01],
       [ 8.20596229e+02],
       [-2.39678199e+01],
       [ 4.40727265e+01],
       [ 2.38712592e+00],
       [ 4.40727265e+01],
       [-1.03204912e+02],
       [ 2.47333093e+02],
       [ 2.16796353e+01],
       [ 6.40542541e+01],
       [ 8.14395065e+02],
       [ 2.91947021e+02],
       [ 1.70679819e+02],
       [ 2.68175893e+02],
       [-9.21806209e+01],
       [ 1.12802291e+02],
       [ 1.00042998e+03],
       [-5.22175658e+01],
       [-1.22669676e+02],
       [-1.0

In [8]:
## Add a new column so we can build the chart
sales.insert(3,'Predicted profit', sales_predict)

In [9]:
## Rearrange the columns
sales = sales[['Customer Name', 'Sales', 'Profit', 'Predicted profit']]
sales

Customer Name  Sales  Profit  Predicted profit
0           Aaron Bergman    886     129         14.789453
1           Aaron Hawkins   1745     365        162.756110
2          Aaron Smayling   3051    -254        387.720550
3         Adam Bellavance   7756    2055       1198.178198
4               Adam Hart   3250     281        421.999205
5      Adam Shillingsburg   3255      65        422.860478
6           Adrian Barton  14474    5445       2355.384251
7             Adrian Hane   1736      -2        161.205819
8            Adrian Shami     59      22       -127.665058
9             Aimee Bixby    967     314         28.742072
10            Alan Barnes   1114     221         54.063490
11         Alan Dominguez   6107    1870        914.130448
12            Alan Haines   1587    -379        135.539892
13             Alan Hwang   4805    1309        689.855027
14      Alan Schoenberger   4261     720        596.148553
15           Alan Shonely    585      34        -37.059166
16   Alejandro Ballentine    915     265         19.784835
17        Alejandro Grove   2583     733        307.105421
18       Alejandro Savely   3214     355        415.798041
19    Aleksandra Gannaway    368      59        -74.438402
20             Alex Avila   5564    -363        820.596229
21           Alex Grayson    661      -5        -23.967820
22           Alex Russell   1056    -221         44.072727
23         Alice McCarthy    814     195          2.387126
24           Allen Armold   1056     277         44.072727
25         Allen Goldenen    201      69       -103.204912
26       Allen Rosenblatt   2236     -99        247.333093
27          Alyssa Crouse    926     -62         21.679635
28            Alyssa Tate   1172     101         64.054254
29                Amy Cox   5528    1366        814.395065
..                    ...    ...     ...               ...
763         Tony Molinari   1095     293         50.790654
764            Tony Sayre   2243      11        248.538875
765       Tracy Blumstein   4737   -1603        678.141718
766         Tracy Collins    743     218         -9.842947
767         Tracy Hopkins   4234    -572        591.497680
768          Tracy Poddar   1937     139        195.828983
769             Tracy Zic   1707     225        156.210437
770        Troy Blackwell   1388    -136        101.261236
771          Troy Staebel   2820    -295        347.929749
772           Trudy Brown   2798     380        344.140149
773          Trudy Glocke   2075     366        219.600111
774         Trudy Schmidt   3368     221        442.325241
775     Valerie Dominguez   6442    1618        971.835722
776       Valerie Mitchum   2455     514        285.056839
777      Valerie Takahito   1737    -224        161.378074
778        Vicky Freymann    848     -96          8.243781
779          Victor Preis    994     205         33.392945
780      Victoria Brennan   2006     371        207.714547
781      Victoria Pisteka   3361   -1019        441.119460
782       Victoria Wilson   6134    -875        918.781321
783        Vivek Gonzalez    846     144          7.899271
784           Vivek Grady    427     -52        -64.275384
785      Vivek Sundaresam   1056    -263         44.072727
786         Vivian Mathis    381     117        -72.199093
787         William Brown   6160     714        923.259939
788          Xylona Preis   2375     621        271.276475
789         Yana Sorensen   6720    1778       1019.722486
790        Yoseph Carroll   5454    1306        801.648229
791      Zuschuss Carroll   8026   -1032       1244.686926
792    Zuschuss Donatelli   1494     249        119.520219

[793 rows x 4 columns]

In [10]:
## Plot the data with the fitted line
import matplotlib.pyplot as plt
plt.scatter(sales['Sales'], sales['Profit'],  color='orange')
plt.plot(sales['Sales'], sales['Predicted profit'], color='red', linewidth=3)
plt.show()

<Figure size 640x480 with 1 Axes>

In [11]:
## Create a function that wraps the prediction
def predictProfit(sales):
    return model.predict(sales).tolist()

In [12]:
## Test the function
predictProfit(2000)

[[206.68101981954504]]

In [13]:
## Make a connection to the tabpy server
import tabpy_client
connection = tabpy_client.Client("http://localhost:9004")

In [14]:
connection

<Client object at 0x1c7bd2ca908 connected to 'http://localhost:9004'>

In [16]:
## Deploy the model to the tabpy server
connection.deploy('PredictProfit', predictProfit, 'The function to predict profit based on sales number.',override=True)